apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: llm-infra-patch.yaml
    target:
      kind: LLMInferenceService
      name: gpt-oss-20b
