apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-guidellm

resources:
  - namespace.yaml
  - pod.yaml
  # - pvc.yaml

# generatorOptions:
#   disableNameSuffixHash: true

# configMapGenerator:
# - name: tokenizer
#   files:
#   - tokenizer.json
#   - tokenizer_config.json
