apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
  - gateway-api.yaml
  # - ../../operators/cert-manager
  # - ../../operators/leader-worker-set
  - ../../operators/rhoai
  - ../../operators/serverless
  - ../../operators/servicemeshoperator3/operator/overlays/stable
